# ImageN Jekyll Configuration
exclude:  README.md

# Theme
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

# Theme configuration
title: Eclipse ImageN
description: Java Image Processing API
search_enabled: true
aux_links:
    "Eclipse Project":
      - "https://projects.eclipse.org/projects/technology.imagen"
    "GitHub":
      - "http://github.com/eclipse/imagen"
      
# site configuration

imagen_version: "0.4-SNAPSHOT"