<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.imagen</groupId>
    <artifactId>imagen</artifactId>
    <version>0.9.3</version>
  </parent>
  <artifactId>imagen-bom</artifactId>
  <packaging>pom</packaging>
  <name>${project.groupId}:${project.artifactId}</name>
  <description>ImageN Bill of Materials, manages versions of the supported ImageN modules for downstream projects.</description>

  <dependencyManagement>
    <dependencies>
      <!-- core library -->
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-utilities</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-iterators</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-concurrent-tile-cache</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-test-support</artifactId>
        <version>${project.version}</version>
      </dependency>
      <!-- operations -->
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-affine</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-algebra</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-artifact</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-bandcombine</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-bandmerge</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-bandselect</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-binarize</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-border</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-buffer</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-clamp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-classbreaks</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-classifier</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-colorconvert</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-colorindexer</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-contour</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-convolve</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-crop</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-errordiffusion</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-format</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-imagefunction</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-imageread</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-lookup</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-mosaic</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-nullop</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-orderdither</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-piecewise</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-rescale</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-rlookup</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-scale</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-scale2</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-shadedrelief</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-stats</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-threshold</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-translate</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-vectorbin</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-vectorize</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-warp</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-zonal</artifactId>
        <version>${project.version}</version>
      </dependency>
      <!-- jiffle -->
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-jiffle-language</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-jiffle-op</artifactId>
        <version>${project.version}</version>
      </dependency>
      <!-- tools -->
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-rendered-image-browser</artifactId>
        <version>${project.version}</version>
      </dependency>
      <!-- combined jar -->
      <dependency>
        <groupId>org.eclipse.imagen</groupId>
        <artifactId>imagen-all</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>ossrh</flattenMode>
          <pomElements>
            <dependencyManagement>interpolate</dependencyManagement>
          </pomElements>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <goals>
              <goal>flatten</goal>
            </goals>
            <phase>process-resources</phase>
          </execution>
          <execution>
            <id>flatten-clean</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>clean</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
