name: Downstream integration build (GeoWebCache and GeoServer)

on:
  # trigger on PR, but only on main branch, the checkouts of the downstream projects are also targeting main (default branch)
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dspotless.apply.skip=true -Dpom.fmt.skip=true -Dmaven.javadoc.skip=true

jobs:
  integration-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        experimental: [ false ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Checkout imagen (PR) into imagen
        uses: actions/checkout@v4
        with:
          # Ensure we build the *actual PR head* even for forked PRs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: imagen
          fetch-depth: 0
      - name: Maven repository caching
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: gt-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            gt-maven-
      - name: Disable checksum offloading
        # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
        run: |
          sudo ethtool -K eth0 tx off rx off
      - name: Build ImageN
        run: |
          cd imagen
          mvn -B clean install -T1C -DskipTests
      - name: Checkout GeoTools, GeoWebCache, GeoServer and more
        run: |
          cd ~
          echo "Preparing git ssh checkouts"
          mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          echo "Checkout out ImageIO-Ext"
          mkdir imageio-ext
          git clone --quiet --filter=tree:0 https://github.com/geosolutions-it/imageio-ext.git imageio-ext
          echo "Checking out GeoTools"
          mkdir geotools
          git clone --quiet --filter=tree:0 https://github.com/geotools/geotools.git geotools
          echo "Checking out mapfish-print-v2"
          mkdir mapfish-print-v2
          git clone --quiet --filter=tree:0 https://github.com/mapfish/mapfish-print-v2.git mapfish-print-v2
          echo "Checking out GeoWebCache"
          mkdir geowebcache
          git clone --quiet --filter=tree:0 https://github.com/GeoWebCache/geowebcache.git geowebcache
          echo "Checking out GeoServer"
          mkdir geoserver
          git clone --quiet --filter=tree:0 https://github.com/geoserver/geoserver.git geoserver
      - name: Build ImageIO-Ext with tests
        continue-on-error: ${{ matrix.experimental }}
        run: |
          cd ~
          export IMAGEN_VERSION=$(mvn -f ${GITHUB_WORKSPACE}/imagen/pom.xml -N -q -ntp -DforceStdout help:evaluate -Dexpression=project.version)
          cd imageio-ext
          git checkout jai-rename
          echo "Updating ImageN version to ${IMAGEN_VERSION} in ImageIO-Ext"
          ant -f ${{ github.workspace }}/imagen/docs/migration/pom-update.xml -Dproject.dir=`pwd` pom2
          # git diff # show the dependency changes
          ant -f ${{ github.workspace }}/imagen/docs/migration/code-update.xml -Dproject.dir=`pwd` update2
          mvn -B clean install -T1C -fae -Dall
      - name: Build GeoTools v2 with tests
        continue-on-error: ${{ matrix.experimental }}
        run: |
          cd ~
          export IMAGEN_VERSION=$(mvn -f ${GITHUB_WORKSPACE}/imagen/pom.xml -N -q -ntp -DforceStdout help:evaluate -Dexpression=project.version)
          cd geotools
          git checkout jai-rename
          echo "Updating ImageN version to ${IMAGEN_VERSION} in GeoTools"
          ant -f ${{ github.workspace }}/imagen/docs/migration/pom-update.xml -Dproject.dir=`pwd` pom2
          ant -f ${{ github.workspace }}/imagen/docs/migration/code-update.xml -Dproject.dir=`pwd` update2
          mvn -B clean install -T1C -Dall -fae -nsu -Dspotless.apply.skip=true
      - name: Build GeoWebCache with tests
        continue-on-error: ${{ matrix.experimental }}
        run: |
          export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10"
          export MAVEN_OPTS="-Xmx1024m $TEST_OPTS"
          cd ~
          cd geowebcache/geowebcache
          git checkout jai-rename
          ant -f ${{ github.workspace }}/imagen/docs/migration/pom-update.xml -Dproject.dir=`pwd` pom2
          ant -f ${{ github.workspace }}/imagen/docs/migration/code-update.xml -Dproject.dir=`pwd` update2
          mvn -B install -nsu -Dspotless.apply.skip=true -T1C -fae
      - name: Build Mapfish-print v2 with tests
        continue-on-error: ${{ matrix.experimental }}
        run: |
          cd ~
          cd mapfish-print-v2
          git checkout jai-rename
          ant -f ${{ github.workspace }}/imagen/docs/migration/pom-update.xml -Dproject.dir=`pwd` pom2
          ant -f ${{ github.workspace }}/imagen/docs/migration/code-update.xml -Dproject.dir=`pwd` update2
          mvn -B install -nsu -T1C -fae
      - name: Build GeoServer with tests
        continue-on-error: ${{ matrix.experimental }}
        run: |
          echo "Building GeoServer"
          export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10"
          export MAVEN_OPTS="-Xmx512m $TEST_OPTS"
          cd ~
          cd geoserver/src
          git checkout jai-rename
          sed -i "s/<mf.version>2.2.0<\/mf.version>/<mf.version>2.3-SNAPSHOT<\/mf.version>/g" pom.xml
          sed -i "s/<gf.version>3.6.0<\/gf.version>/<gf.version>3.6-SNAPSHOT<\/gf.version>/g" pom.xml
          ant -f ${{ github.workspace }}/imagen/docs/migration/pom-update.xml -Dproject.dir=`pwd` pom2
          ant -f ${{ github.workspace }}/imagen/docs/migration/code-update.xml -Dproject.dir=`pwd` update2
          mvn -B -f pom.xml install -nsu -Prelease -Dspotless.apply.skip=true -T1C -fae
          echo "Building GeoServer Community Modules"
          mvn -B -f community/pom.xml install -nsu -DcommunityRelease -Dspotless.apply.skip=true -DskipTests -T1C -fae
      - name: Remove integration checkouts
        if: always()
        run: |
          cd ~
          echo "Removing clone geotools, geoserver, mapfish-print-v2, geowebcache"
          rm -rf imageio-ext geotools geoserver mapfish-print-v2 geowebcache
      - name: Remove SNAPSHOT jars from repository
        if: always()
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
